// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYRUspJltdZ6C8WqbGnyPuIWmUQYAcQU',
    appId: '1:1084046967536:web:7ae67cdbaa644b99223835',
    messagingSenderId: '1084046967536',
    projectId: 'e-commerce-cfc9c',
    authDomain: 'e-commerce-cfc9c.firebaseapp.com',
    storageBucket: 'e-commerce-cfc9c.appspot.com',
    measurementId: 'G-CQC1VDCRV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BrKt6LM5g4c8nQVO4jenmi1AQjCrvdI',
    appId: '1:1084046967536:android:ff52d5be3f5872a3223835',
    messagingSenderId: '1084046967536',
    projectId: 'e-commerce-cfc9c',
    storageBucket: 'e-commerce-cfc9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjtg_PPDyKQWB6MBr92PlgP7e9cLX9fA',
    appId: '1:1084046967536:ios:13445330308b4e5a223835',
    messagingSenderId: '1084046967536',
    projectId: 'e-commerce-cfc9c',
    storageBucket: 'e-commerce-cfc9c.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjtg_PPDyKQWB6MBr92PlgP7e9cLX9fA',
    appId: '1:1084046967536:ios:13445330308b4e5a223835',
    messagingSenderId: '1084046967536',
    projectId: 'e-commerce-cfc9c',
    storageBucket: 'e-commerce-cfc9c.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
